services:
  app:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    expose:
      - "2000"
    networks:
      - pokebin

  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=pokebin
      - POSTGRES_PASSWORD=pokebin
      - POSTGRES_DB=pokebin
    ports:
      - 5432:5432
    volumes:
      - ./psql:/var/lib/postgresql/data
    networks:
      - pokebin

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - app
      - db
    ports:
      - 6868:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - pokebin

networks:
  pokebin:
    driver: bridge